name: Test Cliff Notes

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.12
          cache: 'pip'
      - name: Install Git-cliff
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi
      - name: Generate changelog
        id: git-cliff
        run: |
          git-cliff --verbose --bump -o CHANGELOG.md

      - name: Commit
        run: |
          git checkout main
          git config user.name 'nickscip'
          git config user.email 'nickscip@gmail.com'
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main

      - name: Upload the binary releases
        uses: svenstaro/upload-release-action@v2
        with:
          file: binary_release.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: 
          body: ${{ steps.git-cliff.outputs.content }}
